name: Sync MAS-Bootstrap Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/massgravel/massgravel.github.io.git
          git fetch upstream
          git checkout main

      - name: Merge upstream changes while preserving custom changes
        run: |
          git merge upstream/main -X ours --allow-unrelated-histories || git merge --abort
          if [ $? -ne 0 ]; then
            echo "Merge conflict detected. Please resolve conflicts manually."
            exit 1
          fi

      - name: Push changes to your fork
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
